# Generated by Django 4.1.6 on 2023-03-04 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpassword',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='passwords.site'),
        ),
    ]
